# -*- coding: utf-8 -*-
"""fit-fit-go.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXASoaamZLa5oT6kuIym4ssSpTV40HEZ
"""

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
import pickle as pkl

data = "/content/drive/MyDrive/Fit-Fit-Go/Dataset.csv"
data = pd.read_csv(data)
data



x = data.drop("calories_to_maintain_weight",axis=1)
y = data["calories_to_maintain_weight"]

x['gender'] = x['gender'].map({'F': 0, 'M': 1})

x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2)

model = RandomForestRegressor()

model.fit(x_train,y_train)

model.predict(x_test[:5])

y_test[:5]

model_pkl_file = "fit-fit-go.pkl"

with open(model_pkl_file, 'wb') as file:
    pkl.dump(model, file)

